version: 0.2
env:
  variables:
    # CSPM settings
    CSPM_URL: "cspm.demo.accuknox.com"
    TENANT_ID: "3730"
    LABEL: "SASTSEMGREP"
    # Repository to scan and branch details
    TARGET_REPO: "https://github.com/NikhilRawat014/leaky-repo"
    BRANCH: "semgrep-sast"
  secrets-manager:
    AK_TOKEN: "AccuKnoxAPIToken:AccuKnoxAPIToken"

phases:
  pre_build:
    commands:
      - echo "Cloning repository..."
      - git clone --single-branch --branch $BRANCH $TARGET_REPO app
      - chmod -R 777 app

  build:
    commands:
      - echo "Running Semgrep scan..."
      - |
        # Run the secrets scan with all constructed flags.
        docker run --rm -v $(pwd)/app:/src returntocorp/semgrep semgrep --config=auto --json > semgrep-results.json

  post_build:
    commands:
      - echo "Uploading report to CSPM panel..."
      - |
        curl -v --location --request POST "https://${CSPM_URL}/api/v1/artifact/?tenant_id=${TENANT_ID}&data_type=SG&save_to_s3=true&label_id=${LABEL}" \
          --header "Tenant-Id: ${TENANT_ID}" \
          --header "Authorization: Bearer ${AK_TOKEN}" \
          --form "file=@$(pwd)/semgrep-results.json"
        
artifacts:
  files:
    - semgrep-results.json
