version: 0.2
env:
  variables:
    # CSPM settings
    CSPM_URL: "cspm.demo.accuknox.com"
    TENANT_ID: "3730"
    LABEL: "SECRETSCAN"
    # Repository to scan and branch details
    TARGET_REPO: "https://github.com/NikhilRawat014/leaky-repo"
    BRANCH: "master"
  secrets-manager:
    AK_TOKEN: "AccuKnoxAPIToken"

phases:
  pre_build:
    commands:
      - echo "Cloning repository..."
      - git clone --single-branch --branch $BRANCH $TARGET_REPO app
      - chmod -R 777 app

  build:
    commands:
      - echo "Running TruffleHog scan..."
      - |
        # Run the secrets scan with all constructed flags.
        docker run --rm -v $(pwd)/app:/pwd trufflesecurity/trufflehog:3.88.1 git file:///pwd \
          --json --no-update > trufflehog-results.json

  post_build:
    commands:
      - echo "Verifying generated file..."
      - ls -la
      - cat trufflehog-results.json
      - echo "Uploading report to CSPM panel..."
      - |
        RESPONSE=$(curl --location --request POST "https://${CSPM_URL}/api/v1/artifact/?tenant_id=${TENANT_ID}&data_type=TruffleHog&save_to_s3=true&label_id=${LABEL}" \
          --header "Tenant-Id: ${TENANT_ID}" \
          --header "Authorization: Bearer ${AK_TOKEN}" \
          --form "file=@$(pwd)/trufflehog-results.json")
        echo "Server response: $RESPONSE"
artifacts:
  files:
    - trufflehog-results.json
