version: 0.2
env:
  variables:
    # CSPM settings
    CSPM_URL: "cspm.demo.accuknox.com"
    TENANT_ID: "3730"
    LABEL: "SECRETSCAN"
    # Repository to scan and branch details
    TARGET_REPO: "https://github.com/NikhilRawat014/leaky-repo"
    BRANCH: "master"
    # Optional flags (leave empty if not needed)
    RESULTS: ""
    FAIL: "false"          # Set to "true" to fail the build if secrets are found
    EXCLUDE_PATHS: ""
    ARGS: ""
  secrets-manager:
    AK_TOKEN: "AK_TOKEN:AK_TOKEN"

phases:
  pre_build:
    commands:
      - echo "Cloning repository..."
      - git clone --single-branch --branch $BRANCH $TARGET_REPO app
      - chmod -R 777 app

  build:
    commands:
      - echo "Preparing TruffleHog flags..."
      - |
        BRANCH_FLAG=""
        if [ -n "$BRANCH" ]; then
          if [ "$BRANCH" != "all-branches" ]; then
            BRANCH_FLAG="--branch=$BRANCH"
          fi
        fi
      - |
        RESULTS_FLAG=""
        if [ -n "$RESULTS" ]; then
          RESULTS_FLAG="--results $RESULTS"
        fi
      - |
        FAIL_FLAG=""
        if [ "$FAIL" == "true" ]; then
          FAIL_FLAG="--fail"
        fi
      - |
        EXCLUDE_FLAG=""
        if [ -n "$EXCLUDE_PATHS" ]; then
          EXCLUDE_FLAG="-x /pwd/$EXCLUDE_PATHS"
        fi
      - |
        EXTRA_ARGS=""
        if [ -n "$ARGS" ]; then
          EXTRA_ARGS="$ARGS"
        fi
      - echo "Running TruffleHog scan..."
      - |
        # Run the secrets scan with all constructed flags.
        docker run --rm -v $(pwd)/app:/pwd trufflesecurity/trufflehog:3.88.1 git file:///pwd --json --no-update $BRANCH_FLAG $RESULTS_FLAG $FAIL_FLAG $EXCLUDE_FLAG $EXTRA_ARGS > trufflehog-results.json
        EXIT_CODE=$?
        echo $EXIT_CODE > trufflehog_exit_code.txt
        echo "TruffleHog exit code: $EXIT_CODE"

  post_build:
    commands:
      - echo "Evaluating TruffleHog scan results..."
      - |
        EXIT_CODE=$(cat trufflehog_exit_code.txt)
        if [ "$EXIT_CODE" == "183" ]; then
          echo "TruffleHog detected secrets. Failing the job."
          exit 1
        fi
      - echo "Checking if any secrets were found..."
      - if [ ! -s trufflehog-results.json ]; then echo "No secrets found. Skipping API upload."; exit 0; fi
      - echo "Uploading report to CSPM panel..."
      - |
        RESPONSE=$(curl --location --request POST "https://${CSPM_URL}/api/v1/artifact/?tenant_id=${TENANT_ID}&data_type=TruffleHog&save_to_s3=true&label_id=${LABEL}" \
          --header "Tenant-Id: ${TENANT_ID}" \
          --header "Authorization: Bearer ${AK_TOKEN}" \
          --form "file=@$(pwd)/trufflehog-results.json")
        echo "Response: $RESPONSE"
        if [[ "$RESPONSE" != *"File received successfully"* ]]; then
          echo "Error: Failed to upload report to CSPM panel"
          exit 1
        fi

artifacts:
  files:
    - trufflehog-results.json
